% This script is written and read by pdetool and should NOT be edited.
% There are two recommended alternatives:
 % 1) Export the required variables from pdetool and create a MATLAB script
 %    to perform operations on these.
 % 2) Define the problem completely using a MATLAB script. See
 %    http://www.mathworks.com/help/pde/examples/index.html for examples
 %    of this approach.
function pdemodel
[pde_fig,ax]=pdeinit;
pdetool('appl_cb',1);
set(ax,'DataAspectRatio',[1 1.3125 1]);
set(ax,'PlotBoxAspectRatio',[8 5.333333333333333 1]);
set(ax,'XLim',[-3 13]);
set(ax,'YLim',[-2 12]);
set(ax,'XTickMode','auto');
set(ax,'YTickMode','auto');
pdetool('gridon','on');

% Geometry description:
pderect([0 10 9 0],'R1');
pderect([3 6 2 0],'R2');
pderect([3 6 7 4],'R3');
pderect([-2 0 8 7],'R4');
pderect([10 12 8 7],'R5');
set(findobj(get(pde_fig,'Children'),'Tag','PDEEval'),'String','(R1+R4+R5)-(R3+R2)')

% Boundary conditions:
pdetool('changemode',0)
pdesetbd(22,...
'dir',...
1,...
'1',...
'10')
pdesetbd(20,...
'dir',...
1,...
'1',...
'10')
pdesetbd(19,...
'dir',...
1,...
'1',...
'0')
pdesetbd(18,...
'dir',...
1,...
'1',...
'0')
pdesetbd(17,...
'dir',...
1,...
'1',...
'10')
pdesetbd(16,...
'dir',...
1,...
'1',...
'10')
pdesetbd(15,...
'dir',...
1,...
'1',...
'10')
pdesetbd(13,...
'dir',...
1,...
'1',...
'10')
pdesetbd(12,...
'dir',...
1,...
'1',...
'10')
pdesetbd(11,...
'dir',...
1,...
'1',...
'0')
pdesetbd(10,...
'dir',...
1,...
'1',...
'10')
pdesetbd(9,...
'dir',...
1,...
'1',...
'10')
pdesetbd(8,...
'dir',...
1,...
'1',...
'10')
pdesetbd(7,...
'dir',...
1,...
'1',...
'0')
pdesetbd(6,...
'dir',...
1,...
'1',...
'10')
pdesetbd(5,...
'dir',...
1,...
'1',...
'10')
pdesetbd(4,...
'dir',...
1,...
'1',...
'10')
pdesetbd(3,...
'dir',...
1,...
'1',...
'10')
pdesetbd(2,...
'dir',...
1,...
'1',...
'10')
pdesetbd(1,...
'dir',...
1,...
'1',...
'10')

% Mesh generation:
setappdata(pde_fig,'Hgrad',1.3);
setappdata(pde_fig,'refinemethod','regular');
setappdata(pde_fig,'jiggle',char('on','mean',''));
setappdata(pde_fig,'MesherVersion','preR2013a');
pdetool('initmesh')
pdetool('refine')

% PDE coefficients:
pdeseteq(1,...
'1.0',...
'0.0',...
'0',...
'1.0',...
'0:10',...
'0.0',...
'0.0',...
'[0 100]')
setappdata(pde_fig,'currparam',...
['1.0';...
'0.0';...
'0  ';...
'1.0'])

% Solve parameters:
setappdata(pde_fig,'solveparam',...
char('0','1000','10','pdeadworst',...
'0.5','longest','0','1E-4','','fixed','Inf'))

% Plotflags and user data strings:
setappdata(pde_fig,'plotflags',[1 1 1 1 1 1 7 1 0 0 0 1 1 0 0 1 0 1]);
setappdata(pde_fig,'colstring','');
setappdata(pde_fig,'arrowstring','');
setappdata(pde_fig,'deformstring','');
setappdata(pde_fig,'heightstring','');

% Solve PDE:
pdetool('solve')
